// GAUL 2024 Level 0 — static lookup table
// Source: ee.FeatureCollection("projects/sat-io/open-datasets/FAO/GAUL/GAUL_2024_L0")
// Generated via modules/extract_gaul_lut.js
//
// Usage:
//   var gaul = require('...path...:modules/gaulLut');
//   var names = gaul.country_names;          // sorted name array for dropdowns
//   var code  = gaul.nameToCode('Kenya');     // 137
//   var info  = gaul.GAUL_LUT[137];           // {name: "Kenya", iso3: "KEN"}
//   var img   = gaul.getCountryMask(137);     // ee.Image mask for Kenya

// ── Full LUT: gaul0_code → {name, iso3} ─────────────────────────────
var GAUL_LUT = {
  100: {name: "Abyei", iso3: "xAB"},
  101: {name: "Algeria", iso3: "DZA"},
  102: {name: "Angola", iso3: "AGO"},
  103: {name: "Ascension, Saint Helena and Tristan da Cunha", iso3: "SHN"},
  104: {name: "Bassas Da India", iso3: "xFR"},
  105: {name: "Benin", iso3: "BEN"},
  106: {name: "Botswana", iso3: "BWA"},
  107: {name: "Bouvet Island", iso3: "BVT"},
  108: {name: "Burkina Faso", iso3: "BFA"},
  109: {name: "Burundi", iso3: "BDI"},
  110: {name: "Bīr Ṭawīl", iso3: "xMS"},
  111: {name: "Cabo Verde", iso3: "CPV"},
  112: {name: "Cameroon", iso3: "CMR"},
  113: {name: "Central African Republic", iso3: "CAF"},
  114: {name: "Chad", iso3: "TCD"},
  115: {name: "Comoros", iso3: "COM"},
  116: {name: "Congo", iso3: "COG"},
  117: {name: "Côte D'Ivoire", iso3: "CIV"},
  118: {name: "Democratic Republic of the Congo", iso3: "COD"},
  119: {name: "Djibouti", iso3: "DJI"},
  120: {name: "Egypt", iso3: "EGY"},
  121: {name: "Equatorial Guinea", iso3: "GNQ"},
  122: {name: "Eritrea", iso3: "ERI"},
  123: {name: "Eswatini", iso3: "SWZ"},
  124: {name: "Ethiopia", iso3: "ETH"},
  125: {name: "Europa Island", iso3: "xFR"},
  126: {name: "French Southern Territories", iso3: "ATF"},
  127: {name: "Gabon", iso3: "GAB"},
  128: {name: "Gambia", iso3: "GMB"},
  129: {name: "Ghana", iso3: "GHA"},
  130: {name: "Glorioso Islands", iso3: "xFR"},
  131: {name: "Guinea", iso3: "GIN"},
  132: {name: "Guinea-Bissau", iso3: "GNB"},
  133: {name: "Hala'Ib Triangle", iso3: "xHT"},
  134: {name: "Heard Isl. & McDonald Is. (Aust.)", iso3: "HMD"},
  135: {name: "Ilemi Triangle", iso3: "xIT"},
  136: {name: "Juan De Nova Island", iso3: "xFR"},
  137: {name: "Kenya", iso3: "KEN"},
  138: {name: "Lesotho", iso3: "LSO"},
  139: {name: "Liberia", iso3: "LBR"},
  140: {name: "Libya", iso3: "LBY"},
  141: {name: "Madagascar", iso3: "MDG"},
  142: {name: "Malawi", iso3: "MWI"},
  143: {name: "Mali", iso3: "MLI"},
  144: {name: "Mauritania", iso3: "MRT"},
  145: {name: "Mauritius", iso3: "MUS"},
  146: {name: "Mayotte", iso3: "MYT"},
  147: {name: "Morocco", iso3: "MAR"},
  148: {name: "Mozambique", iso3: "MOZ"},
  149: {name: "Namibia", iso3: "NAM"},
  150: {name: "Niger", iso3: "NER"},
  151: {name: "Nigeria", iso3: "NGA"},
  152: {name: "Rwanda", iso3: "RWA"},
  153: {name: "Réunion", iso3: "REU"},
  154: {name: "Sao Tome And Principe", iso3: "STP"},
  155: {name: "Senegal", iso3: "SEN"},
  156: {name: "Seychelles", iso3: "SYC"},
  157: {name: "Sierra Leone", iso3: "SLE"},
  158: {name: "Somalia", iso3: "SOM"},
  159: {name: "South Africa", iso3: "ZAF"},
  160: {name: "South Sudan", iso3: "SSD"},
  161: {name: "Sudan", iso3: "SDN"},
  162: {name: "Togo", iso3: "TGO"},
  163: {name: "Tromelin Island", iso3: "xFR"},
  164: {name: "Tunisia", iso3: "TUN"},
  165: {name: "Uganda", iso3: "UGA"},
  166: {name: "United Republic of Tanzania", iso3: "TZA"},
  167: {name: "Western Sahara", iso3: "ESH"},
  168: {name: "Zambia", iso3: "ZMB"},
  169: {name: "Zimbabwe", iso3: "ZWE"},
  170: {name: "Anguilla", iso3: "AIA"},
  171: {name: "Antigua And Barbuda", iso3: "ATG"},
  172: {name: "Argentina", iso3: "ARG"},
  173: {name: "Aruba", iso3: "ABW"},
  174: {name: "Bahamas", iso3: "BHS"},
  175: {name: "Barbados", iso3: "BRB"},
  176: {name: "Belize", iso3: "BLZ"},
  177: {name: "Bermuda", iso3: "BMU"},
  178: {name: "Bolivia (Plurinational State of)", iso3: "BOL"},
  179: {name: "Bonaire, Sint Eustatius And Saba", iso3: "BES"},
  180: {name: "Brazil", iso3: "BRA"},
  181: {name: "British Virgin Islands", iso3: "VGB"},
  182: {name: "Canada", iso3: "CAN"},
  183: {name: "Cayman Islands", iso3: "CYM"},
  184: {name: "Chile", iso3: "CHL"},
  185: {name: "Colombia", iso3: "COL"},
  186: {name: "Costa Rica", iso3: "CRI"},
  187: {name: "Cuba", iso3: "CUB"},
  188: {name: "Dominica", iso3: "DMA"},
  189: {name: "Dominican Republic", iso3: "DOM"},
  190: {name: "Ecuador", iso3: "ECU"},
  191: {name: "El Salvador", iso3: "SLV"},
  192: {name: "Falkland Islands (Malvinas)", iso3: "FLK"},
  193: {name: "French Guiana", iso3: "GUF"},
  194: {name: "Grenada", iso3: "GRD"},
  195: {name: "Guadeloupe", iso3: "GLP"},
  196: {name: "Guatemala", iso3: "GTM"},
  197: {name: "Guyana", iso3: "GUY"},
  198: {name: "Haiti", iso3: "HTI"},
  199: {name: "Honduras", iso3: "HND"},
  200: {name: "Jamaica", iso3: "JAM"},
  201: {name: "Martinique", iso3: "MTQ"},
  202: {name: "Mexico", iso3: "MEX"},
  203: {name: "Montserrat", iso3: "MSR"},
  204: {name: "Nicaragua", iso3: "NIC"},
  205: {name: "Panama", iso3: "PAN"},
  206: {name: "Paraguay", iso3: "PRY"},
  207: {name: "Peru", iso3: "PER"},
  208: {name: "Puerto Rico", iso3: "PRI"},
  209: {name: "Saint Barthélemy", iso3: "BLM"},
  210: {name: "Saint Kitts And Nevis", iso3: "KNA"},
  211: {name: "Saint Lucia", iso3: "LCA"},
  212: {name: "Saint Martin (French part)", iso3: "MAF"},
  213: {name: "Saint Pierre and Miquelon", iso3: "SPM"},
  214: {name: "Saint Vincent and the Grenadines", iso3: "VCT"},
  215: {name: "South Georgia and the South Sandwich Islands", iso3: "SGS"},
  216: {name: "Suriname", iso3: "SUR"},
  217: {name: "Trinidad And Tobago", iso3: "TTO"},
  218: {name: "Turks And Caicos Islands", iso3: "TCA"},
  219: {name: "United States Virgin Islands", iso3: "VIR"},
  220: {name: "United States of America", iso3: "USA"},
  221: {name: "Uruguay", iso3: "URY"},
  222: {name: "Venezuela (Bolivarian Republic Of)", iso3: "VEN"},
  223: {name: "Afghanistan", iso3: "AFG"},
  224: {name: "Aksai Chin", iso3: "xAC"},
  225: {name: "Armenia", iso3: "ARM"},
  226: {name: "Arunachal Pradesh", iso3: "xAP"},
  227: {name: "Azerbaijan", iso3: "AZE"},
  228: {name: "Bahrain", iso3: "BHR"},
  229: {name: "Bangladesh", iso3: "BGD"},
  230: {name: "Bhutan", iso3: "BTN"},
  231: {name: "Brunei Darussalam", iso3: "BRN"},
  232: {name: "Cambodia", iso3: "KHM"},
  233: {name: "Chagos Archipelagio", iso3: "IOT"},
  234: {name: "China", iso3: "CHN"},
  235: {name: "China, Hong Kong SAR", iso3: "HKG"},
  236: {name: "China, Macao SAR", iso3: "MAC"},
  237: {name: "Democratic People's Republic of Korea", iso3: "PRK"},
  238: {name: "Disputed Area(xxx)", iso3: "xxx"},
  239: {name: "Disputed Area(xJL)", iso3: "xJL"},
  240: {name: "India", iso3: "IND"},
  241: {name: "Indonesia", iso3: "IDN"},
  242: {name: "Iran (Islamic Republic Of)", iso3: "IRN"},
  243: {name: "Iraq", iso3: "IRQ"},
  244: {name: "Israel", iso3: "ISR"},
  245: {name: "Jammu And Kashmir", iso3: "xJK"},
  246: {name: "Japan", iso3: "JPN"},
  247: {name: "Jordan", iso3: "JOR"},
  248: {name: "Kazakhstan", iso3: "KAZ"},
  249: {name: "Kuril Islands", iso3: "xKI"},
  250: {name: "Kuwait", iso3: "KWT"},
  251: {name: "Kyrgyzstan", iso3: "KGZ"},
  252: {name: "Lao People's Democratic Republic", iso3: "LAO"},
  253: {name: "Lebanon", iso3: "LBN"},
  254: {name: "Malaysia", iso3: "MYS"},
  255: {name: "Maldives", iso3: "MDV"},
  256: {name: "Mongolia", iso3: "MNG"},
  257: {name: "Myanmar", iso3: "MMR"},
  258: {name: "Nepal", iso3: "NPL"},
  259: {name: "Oman", iso3: "OMN"},
  260: {name: "Pakistan", iso3: "PAK"},
  261: {name: "Palestine", iso3: "PSE"},
  262: {name: "Paracel Islands", iso3: "xPI"},
  263: {name: "Philippines", iso3: "PHL"},
  264: {name: "Qatar", iso3: "QAT"},
  265: {name: "Republic Of Korea", iso3: "KOR"},
  266: {name: "Saudi Arabia", iso3: "SAU"},
  267: {name: "Scarborough Reef", iso3: "xSR"},
  268: {name: "Senkaku Islands", iso3: "xSK"},
  269: {name: "Singapore", iso3: "SGP"},
  270: {name: "Spratly Islands", iso3: "xSI"},
  271: {name: "Sri Lanka", iso3: "LKA"},
  272: {name: "Syrian Arab Republic", iso3: "SYR"},
  273: {name: "Taiwan Province of China", iso3: "TWN"},
  274: {name: "Tajikistan", iso3: "TJK"},
  275: {name: "Thailand", iso3: "THA"},
  276: {name: "Timor-Leste", iso3: "TLS"},
  277: {name: "Turkmenistan", iso3: "TKM"},
  278: {name: "Türkiye", iso3: "TUR"},
  279: {name: "United Arab Emirates", iso3: "ARE"},
  280: {name: "Uzbekistan", iso3: "UZB"},
  281: {name: "Viet Nam", iso3: "VNM"},
  282: {name: "Yemen", iso3: "YEM"},
  283: {name: "Akrotiri", iso3: "xUK"},
  284: {name: "Albania", iso3: "ALB"},
  285: {name: "Andorra", iso3: "AND"},
  286: {name: "Austria", iso3: "AUT"},
  287: {name: "Belarus", iso3: "BLR"},
  288: {name: "Belgium", iso3: "BEL"},
  289: {name: "Bosnia and Herzegovina", iso3: "BIH"},
  290: {name: "Bulgaria", iso3: "BGR"},
  292: {name: "Croatia", iso3: "HRV"},
  293: {name: "Curaçao", iso3: "CUW"},
  294: {name: "Cyprus", iso3: "CYP"},
  295: {name: "Czechia", iso3: "CZE"},
  296: {name: "Dekelia", iso3: "xUK"},
  297: {name: "Denmark", iso3: "DNK"},
  298: {name: "Estonia", iso3: "EST"},
  299: {name: "Faroe Islands", iso3: "FRO"},
  300: {name: "Finland", iso3: "FIN"},
  301: {name: "France", iso3: "FRA"},
  302: {name: "Georgia", iso3: "GEO"},
  303: {name: "Germany", iso3: "DEU"},
  304: {name: "Gibraltar", iso3: "GIB"},
  305: {name: "Greece", iso3: "GRC"},
  306: {name: "Guernsey", iso3: "GGY"},
  307: {name: "Holy See", iso3: "VAT"},
  308: {name: "Hungary", iso3: "HUN"},
  309: {name: "Iceland", iso3: "ISL"},
  310: {name: "Ireland", iso3: "IRL"},
  311: {name: "Isle of Man", iso3: "IMN"},
  312: {name: "Italy", iso3: "ITA"},
  313: {name: "Jersey", iso3: "JEY"},
  314: {name: "Latvia", iso3: "LVA"},
  315: {name: "Liechtenstein", iso3: "LIE"},
  316: {name: "Lithuania", iso3: "LTU"},
  317: {name: "Luxembourg", iso3: "LUX"},
  318: {name: "Malta", iso3: "MLT"},
  319: {name: "Monaco", iso3: "MCO"},
  320: {name: "Montenegro", iso3: "MNE"},
  321: {name: "Netherlands (Kingdom of the)", iso3: "NLD"},
  322: {name: "North Macedonia", iso3: "MKD"},
  323: {name: "Norway", iso3: "NOR"},
  324: {name: "Poland", iso3: "POL"},
  325: {name: "Portugal", iso3: "PRT"},
  326: {name: "Republic of Moldova", iso3: "MDA"},
  327: {name: "Romania", iso3: "ROU"},
  328: {name: "Russian Federation", iso3: "RUS"},
  329: {name: "San Marino", iso3: "SMR"},
  330: {name: "Serbia", iso3: "SRB"},
  331: {name: "Sint Maarten (Dutch part)", iso3: "SXM"},
  332: {name: "Slovakia", iso3: "SVK"},
  333: {name: "Slovenia", iso3: "SVN"},
  334: {name: "Spain", iso3: "ESP"},
  335: {name: "Svalbard and Jan Mayen Islands", iso3: "SJM"},
  336: {name: "Sweden", iso3: "SWE"},
  337: {name: "Switzerland", iso3: "CHE"},
  338: {name: "Ukraine", iso3: "UKR"},
  339: {name: "United Kingdom of Great Britain and Northern Ireland", iso3: "GBR"},
  340: {name: "Åland Islands", iso3: "ALA"},
  341: {name: "American Samoa", iso3: "ASM"},
  342: {name: "Ashmore and Cartier Islands", iso3: "AUS"},
  343: {name: "Australia", iso3: "AUS"},
  344: {name: "Christmas Island", iso3: "CXR"},
  345: {name: "Clipperton Island", iso3: "PYF"},
  346: {name: "Cocos (Keeling) Islands", iso3: "CCK"},
  347: {name: "Cook Islands", iso3: "COK"},
  348: {name: "Fiji", iso3: "FJI"},
  349: {name: "French Polynesia", iso3: "PYF"},
  350: {name: "Guam", iso3: "GUM"},
  351: {name: "Kiribati", iso3: "KIR"},
  352: {name: "Marshall Islands", iso3: "MHL"},
  353: {name: "Micronesia (Federated States of)", iso3: "FSM"},
  354: {name: "Nauru", iso3: "NRU"},
  355: {name: "New Caledonia", iso3: "NCL"},
  356: {name: "New Zealand", iso3: "NZL"},
  357: {name: "Niue", iso3: "NIU"},
  358: {name: "Norfolk Island", iso3: "NFK"},
  359: {name: "Northern Mariana Islands", iso3: "MNP"},
  360: {name: "Palau", iso3: "PLW"},
  361: {name: "Papua New Guinea", iso3: "PNG"},
  362: {name: "Pitcairn", iso3: "PCN"},
  363: {name: "Samoa", iso3: "WSM"},
  364: {name: "Solomon Islands", iso3: "SLB"},
  365: {name: "Tokelau", iso3: "TKL"},
  366: {name: "Tonga", iso3: "TON"},
  367: {name: "Tuvalu", iso3: "TUV"},
  368: {name: "United States Minor Outlying Islands", iso3: "UMI"},
  369: {name: "Vanuatu", iso3: "VUT"},
  370: {name: "Wallis and Futuna Islands", iso3: "WLF"},
  371: {name: "Antarctica", iso3: "ATA"},
  372: {name: "Greenland", iso3: "GRL"}
};

exports.GAUL_LUT = GAUL_LUT;

// ── Sorted country name list (for dropdown — no .getInfo() needed) ───
var country_names = [
  "Abyei", "Afghanistan", "Akrotiri", "Aksai Chin", "Albania", "Algeria",
  "American Samoa", "Andorra", "Angola", "Anguilla", "Antarctica",
  "Antigua And Barbuda", "Argentina", "Armenia", "Aruba", "Arunachal Pradesh",
  "Ascension, Saint Helena and Tristan da Cunha", "Ashmore and Cartier Islands",
  "Australia", "Austria", "Azerbaijan", "Bahamas", "Bahrain", "Bangladesh",
  "Barbados", "Bassas Da India", "Belarus", "Belgium", "Belize", "Benin",
  "Bermuda", "Bhutan", "Bolivia (Plurinational State of)",
  "Bonaire, Sint Eustatius And Saba", "Bosnia and Herzegovina", "Botswana",
  "Bouvet Island", "Brazil", "British Virgin Islands", "Brunei Darussalam",
  "Bulgaria", "Burkina Faso", "Burundi", "Bīr Ṭawīl", "Cabo Verde",
  "Cambodia", "Cameroon", "Canada", "Cayman Islands",
  "Central African Republic", "Chad", "Chagos Archipelagio", "Chile", "China",
  "China, Hong Kong SAR", "China, Macao SAR", "Christmas Island",
  "Clipperton Island", "Cocos (Keeling) Islands", "Colombia", "Comoros",
  "Congo", "Cook Islands", "Costa Rica", "Croatia", "Cuba", "Curaçao",
  "Cyprus", "Czechia", "Côte D'Ivoire", "Dekelia",
  "Democratic People's Republic of Korea",
  "Democratic Republic of the Congo", "Denmark", "Disputed Area(xJL)",
  "Disputed Area(xxx)", "Djibouti", "Dominica", "Dominican Republic",
  "Ecuador", "Egypt", "El Salvador", "Equatorial Guinea", "Eritrea",
  "Estonia", "Eswatini", "Ethiopia", "Europa Island",
  "Falkland Islands (Malvinas)", "Faroe Islands", "Fiji", "Finland", "France",
  "French Guiana", "French Polynesia", "French Southern Territories", "Gabon",
  "Gambia", "Georgia", "Germany", "Ghana", "Gibraltar", "Glorioso Islands",
  "Greece", "Greenland", "Grenada", "Guadeloupe", "Guam", "Guatemala",
  "Guernsey", "Guinea", "Guinea-Bissau", "Guyana", "Haiti",
  "Hala'Ib Triangle", "Heard Isl. & McDonald Is. (Aust.)", "Holy See",
  "Honduras", "Hungary", "Iceland", "Ilemi Triangle", "India", "Indonesia",
  "Iran (Islamic Republic Of)", "Iraq", "Ireland", "Isle of Man", "Israel",
  "Italy", "Jamaica", "Jammu And Kashmir", "Japan", "Jersey", "Jordan",
  "Juan De Nova Island", "Kazakhstan", "Kenya", "Kiribati", "Kuril Islands",
  "Kuwait", "Kyrgyzstan", "Lao People's Democratic Republic", "Latvia",
  "Lebanon", "Lesotho", "Liberia", "Libya", "Liechtenstein", "Lithuania",
  "Luxembourg", "Madagascar", "Malawi", "Malaysia", "Maldives", "Mali",
  "Malta", "Marshall Islands", "Martinique", "Mauritania", "Mauritius",
  "Mayotte", "Mexico", "Micronesia (Federated States of)", "Monaco",
  "Mongolia", "Montenegro", "Montserrat", "Morocco", "Mozambique", "Myanmar",
  "Namibia", "Nauru", "Nepal", "Netherlands (Kingdom of the)",
  "New Caledonia", "New Zealand", "Nicaragua", "Niger", "Nigeria", "Niue",
  "Norfolk Island", "North Macedonia", "Northern Mariana Islands", "Norway",
  "Oman", "Pakistan", "Palau", "Palestine", "Panama", "Papua New Guinea",
  "Paracel Islands", "Paraguay", "Peru", "Philippines", "Pitcairn", "Poland",
  "Portugal", "Puerto Rico", "Qatar", "Republic Of Korea",
  "Republic of Moldova", "Romania", "Russian Federation", "Rwanda", "Réunion",
  "Saint Barthélemy", "Saint Kitts And Nevis", "Saint Lucia",
  "Saint Martin (French part)", "Saint Pierre and Miquelon",
  "Saint Vincent and the Grenadines", "Samoa", "San Marino",
  "Sao Tome And Principe", "Saudi Arabia", "Scarborough Reef", "Senegal",
  "Senkaku Islands", "Serbia", "Seychelles", "Sierra Leone", "Singapore",
  "Sint Maarten (Dutch part)", "Slovakia", "Slovenia", "Solomon Islands",
  "Somalia", "South Africa",
  "South Georgia and the South Sandwich Islands", "South Sudan", "Spain",
  "Spratly Islands", "Sri Lanka", "Sudan", "Suriname",
  "Svalbard and Jan Mayen Islands", "Sweden", "Switzerland",
  "Syrian Arab Republic", "Taiwan Province of China", "Tajikistan",
  "Thailand", "Timor-Leste", "Togo", "Tokelau", "Tonga",
  "Trinidad And Tobago", "Tromelin Island", "Tunisia", "Turkmenistan",
  "Turks And Caicos Islands", "Tuvalu", "Türkiye", "Uganda", "Ukraine",
  "United Arab Emirates",
  "United Kingdom of Great Britain and Northern Ireland",
  "United Republic of Tanzania", "United States Minor Outlying Islands",
  "United States Virgin Islands", "United States of America", "Uruguay",
  "Uzbekistan", "Vanuatu", "Venezuela (Bolivarian Republic Of)", "Viet Nam",
  "Wallis and Futuna Islands", "Western Sahara", "Yemen", "Zambia",
  "Zimbabwe", "Åland Islands"
];

exports.country_names = country_names;

// ── Reverse lookup: name → gaul0_code ────────────────────────────────
var _nameToCode = {};
for (var code in GAUL_LUT) {
  _nameToCode[GAUL_LUT[code].name] = Number(code);
}

/**
 * Look up a GAUL code by country name.
 * @param {string} name - Country name (must match GAUL_LUT exactly).
 * @return {number|undefined} gaul0_code or undefined if not found.
 */
var nameToCode = function(name) {
  return _nameToCode[name];
};

exports.nameToCode = nameToCode;

// ── GAUL raster image (500 m, pixel value = gaul0_code) ──────────────
var GAUL_IMAGE_ASSET = "projects/ee-andyarnellgee/assets/gaul_2024_level_0_code_500m";

/**
 * Get a binary mask for a single country from the raster GAUL image.
 * Faster than ee.Image(1).clip(featureCollection) for interactive display.
 * @param {number} gaul0_code - The GAUL code for the country.
 * @return {ee.Image} Binary mask (1 inside country, masked outside).
 */
var getCountryMask = function(gaul0_code) {
  return ee.Image(GAUL_IMAGE_ASSET).eq(gaul0_code).selfMask();
};

exports.getCountryMask = getCountryMask;
